VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define :core1 do |core1|
    core1.vm.box = "coreos-alpha"
    core1.vm.hostname = "core1"
    core1.vm.network "private_network", ip: "172.17.8.101"
  end

  config.vm.define :core2 do |core2|
    core2.vm.box = "coreos-alpha"
    core2.vm.hostname = "core-02"
    core2.vm.network "private_network", ip: "172.17.8.102"
  end

  config.vm.define :core3 do |core3|
    core3.vm.box = "coreos-alpha"
    core3.vm.hostname = "core-03"
    core3.vm.network "private_network", ip: "172.17.8.101"
  end

 end
